// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetClean.Data;

#nullable disable

namespace PetClean.Migrations
{
    [DbContext(typeof(PetCleanContext))]
    partial class PetCleanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PetClean.Models.Cadastro", b =>
                {
                    b.Property<int>("CadastroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CadastroId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereço")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RacaId")
                        .HasColumnType("int");

                    b.Property<double>("Telefone")
                        .HasColumnType("float");

                    b.HasKey("CadastroId");

                    b.HasIndex("RacaId");

                    b.ToTable("Cadastro");
                });

            modelBuilder.Entity("PetClean.Models.Raca", b =>
                {
                    b.Property<int>("RacaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RacaId"), 1L, 1);

                    b.Property<string>("Racas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RacaId");

                    b.ToTable("Raca");
                });

            modelBuilder.Entity("PetClean.Models.Cadastro", b =>
                {
                    b.HasOne("PetClean.Models.Raca", "Racas")
                        .WithMany("Cadastros")
                        .HasForeignKey("RacaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Racas");
                });

            modelBuilder.Entity("PetClean.Models.Raca", b =>
                {
                    b.Navigation("Cadastros");
                });
#pragma warning restore 612, 618
        }
    }
}
